name: tasks
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-34.0.dev

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  shared_preferences: ^2.3.3
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  drift: ^2.22.1
  drift_flutter: ^0.1.0
  path_provider: ^2.1.5
  path: ^1.9.0
  fluttertoast: ^8.2.8
  logger: ^2.5.0
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.22.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
